# Batting Statistics:
Runs Scored: Total runs scored by the player.

Batting Average: Runs scored per innings.

Strike Rate: Runs scored per 100 balls faced.

Centuries: Total centuries (100+ runs) scored.

Half-Centuries: Total half-centuries (50+ runs) scored.

Highest Score: The highest score in an innings.

Balls Faced: Total number of balls faced.

Boundary Count: Number of fours and sixes hit.

# Bowling Statistics:
Wickets Taken: Total wickets taken by the player.

Bowling Average: Runs given per wicket taken.

Economy Rate: Runs conceded per over bowled.

Strike Rate: Balls bowled per wicket taken.

Five-Wicket Hauls: Number of instances of taking five or more wickets in an innings.

Best Bowling Figures: Best performance in a single innings.

Overs Bowled: Total overs bowled.

Maidens: Total maiden overs bowled (overs with no runs conceded).

# Fielding Statistics:
Catches: Total catches taken.

Stumpings: Total stumpings made (for wicketkeepers).

Run-outs: Total run-outs effected.

# All-Rounder Statistics:
Batting and Bowling Average: Combined impact of batting and bowling.

Player Impact Score: A metric to measure the overall impact of a player in matches.

# Additional Factors:
Match Performance: Performance in crucial matches or against specific teams.

Player Form: Recent form and consistency over a period.

Injury History: History of injuries and fitness levels.

Captaincy Record: For players who have captained the team.

Experience: Number of matches played, World Cup appearances.

# Batting Statistics:
Runs Scored: Total runs scored by the player.

Batting Average: Runs scored per innings.

Strike Rate: Runs scored per 100 balls faced.

Centuries: Total centuries (100+ runs) scored.

Half-Centuries: Total half-centuries (50+ runs) scored.

Highest Score: The highest score in an innings.

Balls Faced: Total number of balls faced.

In [26]:
# import modules
import pandas as pd
import numpy as np 
from scipy import stats
import math

In [2]:
# importing Data

batting_data = pd.read_csv("./Data/pre_batting_data.csv")
batting_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8660 entries, 0 to 8659
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   VS                 8660 non-null   object
 1   Player             8660 non-null   object
 2   Â                   8660 non-null   object
 3   Batting Possition  8660 non-null   float64
 4   Match Id           8660 non-null   object
 5   Teaminnings        8660 non-null   object
 6   Runs               8660 non-null   float64
 7   Balls              8660 non-null   float64
 8   Mins               8660 non-null   float64
 9   Fours              8660 non-null   float64
 10  Sixs               8660 non-null   float64
 11  Strike Rate        8660 non-null   float64
dtypes: float64(7), object(5)
memory usage: 812.0+ KB

In [33]:
#Runs Scored: Total runs scored by the player.

print("Total Runs Scored by Each Player".center(50,"-"))
total_runs = batting_data.groupby("Player")["Runs"].sum()
total_runs = pd.DataFrame(total_runs).reset_index()
total_runs.Runs = total_runs.Runs.apply(lambda x: round(x,2))
print(total_runs.head())

#Batting Average: Runs scored per innings.

print("Average Runs Scored by Each Player".center(50,"-"))
average_runs = batting_data.groupby("Player")["Runs"].mean()
average_runs = pd.DataFrame(average_runs).reset_index()
average_runs.Runs = average_runs.Runs.apply(lambda x: round(x,2))
average_runs = average_runs.rename(columns={"Runs":"Average Runs"})
print(average_runs.head())

#Strike Rate: Runs scored per 100 balls faced.

print("Strike Rate by Each Player".center(50,"-"))
strike_rate = batting_data.groupby("Player")["Strike Rate"].mean()
strike_rate = pd.DataFrame(strike_rate).reset_index()
strike_rate["Strike Rate"] = strike_rate["Strike Rate"].apply(lambda x: round(x,2))
print(strike_rate.head())

---------Total Runs Scored by Each Player---------
           Player    Runs
0  AB de Villiers  1207.0
1    Aamer Sohail   598.0
2     Aaqib Javed     8.0
3     Aaron Finch   787.0
4  Aashish Kapoor     0.0
--------Average Runs Scored by Each Player--------
           Player  Average Runs
0  AB de Villiers         54.86
1    Aamer Sohail         37.38
2     Aaqib Javed          2.67
3     Aaron Finch         43.72
4  Aashish Kapoor          0.00
------------Strike Rate by Each Player------------
           Player  Strike Rate
0  AB de Villiers        98.12
1    Aamer Sohail        58.75
2     Aaqib Javed        24.36
3     Aaron Finch        88.29
4  Aashish Kapoor         0.00

In [34]:
#Centuries: Total centuries (100+ runs) scored.

print("Total centuries (100+ runs) scored by Each Player".center(50,"-"))
batting_data["Centuries"] = batting_data["Runs"].apply(lambda x:1 if x>=100 else 0)

total_centuries = batting_data[["Player","Centuries"]]
total_centuries = pd.DataFrame(total_centuries.groupby("Player")["Centuries"].sum()).reset_index()
print(total_centuries.head(),end='\n\n\n')

#Half-Centuries: Total half-centuries (50+ runs) scored.

print("Total half centuries (50+ runs) scored by Each Player".center(50,"-"))
batting_data["Half Centuries"] = batting_data["Runs"].apply(lambda x:1 if x>=50 else 0)

total_Half_centuries = batting_data[["Player","Half Centuries"]]
total_Half_centuries = pd.DataFrame(total_Half_centuries.groupby("Player")["Half Centuries"].sum()).reset_index()
print(total_Half_centuries.head(),end='\n\n\n')

#Highest Score: The highest score in an innings.

print("The highest score in an innings".center(50,"-"))

highest_score = batting_data[["Player","Runs"]]
highest_score = pd.DataFrame(highest_score.groupby("Player")["Runs"].max()).reset_index()
highest_score = highest_score.rename(columns={"Runs":"Highest Run"})
print(highest_score.head(),end='\n\n\n')

Total centuries (100+ runs) scored by Each Player-
           Player  Centuries
0  AB de Villiers          4
1    Aamer Sohail          2
2     Aaqib Javed          0
3     Aaron Finch          3
4  Aashish Kapoor          0


Total half centuries (50+ runs) scored by Each Player
           Player  Half Centuries
0  AB de Villiers              10
1    Aamer Sohail               6
2     Aaqib Javed               0
3     Aaron Finch               7
4  Aashish Kapoor               0


---------The highest score in an innings----------
           Player  Highest Run
0  AB de Villiers        162.0
1    Aamer Sohail        114.0
2     Aaqib Javed          6.0
3     Aaron Finch        153.0
4  Aashish Kapoor          0.0

In [125]:
#Balls Faced: Total number of balls faced.

print("Total number of balls faced by Each Player".center(50,"-"))

no_balls = batting_data[["Player","Balls"]]
no_balls = pd.DataFrame(no_balls.groupby("Player")["Balls"].sum()).reset_index()
no_balls = no_balls.rename(columns={"Balls":"No. of Balls"})
print(no_balls.head(),end='\n\n\n')

#Average Balls Faced: Average number of balls faced.

print("Average number of balls faced by Each Player".center(50,"-"))

avg_balls = batting_data[["Player","Balls"]]
avg_balls = pd.DataFrame(avg_balls.groupby("Player")["Balls"].mean()).reset_index()
avg_balls["Balls"] = avg_balls["Balls"].apply(lambda x : math.ceil(x))
avg_balls = avg_balls.rename(columns={"Balls":"Average Balls Faced"})
print(avg_balls.head(),end='\n\n\n')

----Total number of balls faced by Each Player----
           Player  No. of Balls
0  AB de Villiers        1029.0
1    Aamer Sohail         847.0
2     Aaqib Javed          43.0
3     Aaron Finch         801.0
4  Aashish Kapoor           1.0


---Average number of balls faced by Each Player---
           Player  Average Balls Faced
0  AB de Villiers                   47
1    Aamer Sohail                   53
2     Aaqib Javed                   15
3     Aaron Finch                   45
4  Aashish Kapoor                    1

In [127]:
batting_stats = total_runs.merge(average_runs).merge(strike_rate).merge(total_centuries).merge(total_Half_centuries).merge(highest_score).merge(no_balls).merge(avg_balls)

In [128]:
batting_stats.head()

,Player,Runs,Average Runs,Strike Rate,Centuries,Half Centuries,Highest Run,No. of Balls,Average Balls Faced
0,AB de Villiers,1207.0,54.86,98.12,4,10,162.0,1029.0,47
1,Aamer Sohail,598.0,37.38,58.75,2,6,114.0,847.0,53
2,Aaqib Javed,8.0,2.67,24.36,0,0,6.0,43.0,15
3,Aaron Finch,787.0,43.72,88.29,3,7,153.0,801.0,45
4,Aashish Kapoor,0.0,0.00,0.00,0,0,0.0,1.0,1

In [129]:
batting_stats.to_csv("./Data/Batting Statistics.csv",index=False)

# Bowling Statistics:
Wickets Taken: Total wickets taken by the player.

Bowling Average: Runs given per wicket taken.

Economy Rate: Runs conceded per over bowled.

Strike Rate: Balls bowled per wicket taken.

Five-Wicket Hauls: Number of instances of taking five or more wickets in an innings.

Best Bowling Figures: Best performance in a single innings.

Overs Bowled: Total overs bowled.

Maidens: Total maiden overs bowled (overs with no runs conceded).

In [71]:
bowling_data = pd.read_csv("./Data/pre_bowling_data.csv")
bowling_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5849 entries, 0 to 5848
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   VS           5849 non-null   object
 1   Match Id     5849 non-null   object
 2   Player       5849 non-null   object
 3   Overs        5849 non-null   float64
 4   Teaminnings  5849 non-null   object
 5   Mins         5849 non-null   int64
 6   Given Runs   5849 non-null   int64
 7   Wickets      5849 non-null   int64
 8   ECON         5849 non-null   float64
 9   Dot Balls    5849 non-null   int64
 10  Fours        5849 non-null   int64
 11  Sixs         5849 non-null   int64
 12  Wides        5849 non-null   int64
 13  No Balls     5849 non-null   int64
dtypes: float64(2), int64(8), object(4)
memory usage: 639.9+ KB

In [ ]:
#Wickets Taken: Total wickets taken by the player.


print("Total wickets taken by the player".center(50,"-"))

total_wicket = bowling_data[["Player","Wickets"]]
total_wicket = pd.DataFrame(total_wicket.groupby("Player")["Wickets"].sum()).reset_index()
total_wicket = total_wicket.rename(columns={"Wickets":"No. of Wickets"})
print(total_wicket.head(),end='\n\n\n')

#Bowling Average: Runs given per wicket taken.

print("Runs given per wicket taken".center(50,"-"))
bowling_data["Bowling Average"] = bowling_data.apply(lambda x: x["Given Runs"]/x["Wickets"] if x["Wickets"] !=0 else 0 ,axis=1)
bowling_data["Bowling Average"] = bowling_data["Bowling Average"].apply(lambda x: round(x,2))
bowling_average = bowling_data[["Player","Bowling Average"]]
bowling_average = pd.DataFrame(bowling_average.groupby("Player")["Bowling Average"].mean())
bowling_average = bowling_average.reset_index()
bowling_average["Bowling Average"] = bowling_average["Bowling Average"].apply(lambda x: round(x,2))
print(bowling_average.head(),end='\n\n\n')

#Average Economy Rate: Runs conceded per over bowled.

print("Runs conceded per over bowled".center(50,"-"))
economy_rate = bowling_data[["Player","ECON"]]
economy_rate = pd.DataFrame(economy_rate.groupby("Player")["ECON"].mean())
economy_rate = economy_rate.reset_index()
economy_rate["ECON"] = economy_rate["ECON"].apply(lambda x: round(x,2))
economy_rate = economy_rate.rename(columns={"ECON":"Average ECON"})
print(economy_rate.head())

--------Total wickets taken by the player---------
           Player  No. of Wickets
0  AB de Villiers               4
1    Aamer Sohail               8
2     Aaqib Javed              18
3     Aaron Finch               1
4  Aashish Kapoor               1


-----------Runs given per wicket taken------------
           Player  Bowling Average
0  AB de Villiers            14.38
1    Aamer Sohail            12.31
2     Aaqib Javed            20.63
3     Aaron Finch             6.50
4  Aashish Kapoor            20.50


----------Runs conceded per over bowled-----------
           Player  Average ECON
0  AB de Villiers          5.67
1    Aamer Sohail          5.05
2     Aaqib Javed          4.07
3     Aaron Finch          6.75
4  Aashish Kapoor          4.05

In [107]:
#Total Balls Bowled: Number of balls bowled in inning.

bowling_data["Balls"] = bowling_data.apply(lambda x: (int(str(x["Overs"]).split(".")[0])*6) + int(str(x["Overs"]).split(".")[1]) ,axis=1)

#Average Strike Rate: Balls bowled per wicket taken.

bowling_data["Strike Rate"] = bowling_data.apply(lambda x: round(x["Balls"]/x['Wickets'],2) if x['Wickets']!=0 else 0,axis=1)
print("Balls bowled per wicket taken".center(50,"-"))
average_strike_rate = pd.DataFrame(bowling_data.groupby("Player")["Strike Rate"].mean()).reset_index()
average_strike_rate = average_strike_rate.rename(columns={"Strike Rate":"Average Strike Rate"})
average_strike_rate["Average Strike Rate"] = average_strike_rate["Average Strike Rate"].apply(lambda x:round(x,2))
print(average_strike_rate.head(),end="\n\n\n")

#Five-Wicket Hauls: Number of instances of taking five or more wickets in an innings.

print("Number of instances of taking five or more wickets in an innings".center(50,"-"))
bowling_data["Five Wicket Hauls"] = bowling_data.apply(lambda x:1 if x["Wickets"]>=5 else 0,axis=1)
five_wicket = pd.DataFrame(bowling_data.groupby("Player")["Five Wicket Hauls"].sum()).reset_index()
five_wicket = five_wicket.rename(columns={"Five Wicket Hauls":"Total Five Wicket Hauls"})
print(five_wicket.head(),end="\n\n\n")

#Best Bowling Figures: Best performance in a single innings.
print("Best performance in a single innings".center(50,"-"))
bowling_data["Bowling Figure"] = bowling_data.apply(lambda x : f'{x["Wickets"]}/{x["Given Runs"]}',axis=1)
print(bowling_data.head(),end="\n\n\n")

----------Balls bowled per wicket taken-----------
           Player  Average Strike Rate
0  AB de Villiers                14.25
1    Aamer Sohail                17.08
2     Aaqib Javed                27.97
3     Aaron Finch                 6.00
4  Aashish Kapoor                30.00


Number of instances of taking five or more wickets in an innings
           Player  Total Five Wicket Hauls
0  AB de Villiers                        0
1    Aamer Sohail                        0
2     Aaqib Javed                        0
3     Aaron Finch                        0
4  Aashish Kapoor                        0


-------Best performance in a single innings-------
                         VS  Match Id         Player  Overs Teaminnings  Mins  \
0  Australia VS West Indies  ODI # 33  Dennis Lillee    9.0     England     3
1  Australia VS West Indies  ODI # 33   Gary Gilmour   12.0     England     6
2  Australia VS West Indies  ODI # 33     Max Walker    9.2     England     3
3  Australia VS West Indies  ODI # 33   Jeff Thomson    6.0     England     0
4  Australia VS West Indies  ODI # 33   Geoff Arnold    7.4   Australia     2

   Given Runs  Wickets  ECON  Dot Balls  Fours  Sixs  Wides  No Balls  \
0          26        1  2.88          0      0     0      0         0
1          14        6  1.16          0      0     0      0         0
2          22        3  2.35          0      0     0      0         0
3          17        0  2.83          0      0     0      0         0
4          15        1  1.95          0      0     0      0         0

   Bowling Average  Balls  Strike Rate  Five Wicket Hauls Bowling Figure
0            26.00     54        54.00                  0           1/26
1             2.33     72        12.00                  1           6/14
2             7.33     56        18.67                  0           3/22
3             0.00     36         0.00                  0           0/17
4            15.00     46        46.00                  0           1/15

In [115]:
#Overs Bowled: Total overs bowled.
print("Total overs bowled".center(50,"-"))
overs_bowled = pd.DataFrame(bowling_data.groupby("Player")["Overs"].sum()).reset_index()
overs_bowled = overs_bowled.rename(columns={"Overs":"Total Overs"})
print(overs_bowled.head(),end="\n\n\n")

#Average Balls: Average Balls bowled.

print("Average Balls bowled".center(50,"-"))
average_balls_bowled = pd.DataFrame(bowling_data.groupby("Player")["Balls"].mean()).reset_index()
average_balls_bowled["Balls"] = average_balls_bowled["Balls"].apply(lambda x : round(x,2))
average_balls_bowled = average_balls_bowled.rename(columns={"Balls":"Average Balls"})
print(average_balls_bowled.head(),end="\n\n\n")

#Maidens: Total maiden overs bowled (overs with no runs conceded).

----------------Total overs bowled----------------
           Player  Total Overs
0  AB de Villiers         14.0
1    Aamer Sohail         86.0
2     Aaqib Javed        123.8
3     Aaron Finch          3.0
4  Aashish Kapoor         20.0


---------------Average Balls bowled---------------
           Player  Average Balls
0  AB de Villiers          21.00
1    Aamer Sohail          39.69
2     Aaqib Javed          49.73
3     Aaron Finch           9.00
4  Aashish Kapoor          60.00

In [116]:
bowling_stats = total_wicket.merge(bowling_average).merge(economy_rate).merge(average_strike_rate).merge(five_wicket).merge(average_balls_bowled).merge(overs_bowled)

In [118]:
bowling_stats.head()

,Player,No. of Wickets,Bowling Average,Average ECON,Average Strike Rate,Total Five Wicket Hauls,Average Balls,Total Overs
0,AB de Villiers,4,14.38,5.67,14.25,0,21.00,14.0
1,Aamer Sohail,8,12.31,5.05,17.08,0,39.69,86.0
2,Aaqib Javed,18,20.63,4.07,27.97,0,49.73,123.8
3,Aaron Finch,1,6.50,6.75,6.00,0,9.00,3.0
4,Aashish Kapoor,1,20.50,4.05,30.00,0,60.00,20.0

In [119]:
bowling_stats.to_csv("./Data/Bowling Statistics.csv",index=False)

**Since Some features are added in the data set its better to save then, So we can also use them i any further calculations**

In [121]:
bowling_data.to_csv("./Data/pre_bowling_data.csv",index=False)
batting_data.to_csv("./Data/pre_batting_data.csv",index=False)

In [122]:
bowling_data.head()

,VS,Match Id,Player,Overs,Teaminnings,Mins,Given Runs,Wickets,ECON,Dot Balls,Fours,Sixs,Wides,No Balls,Bowling Average,Balls,Strike Rate,Five Wicket Hauls,Bowling Figure
0,Australia VS West Indies,ODI # 33,Dennis Lillee,9.0,England,3,26,1,2.88,0,0,0,0,0,26.00,54,54.00,0,1/26
1,Australia VS West Indies,ODI # 33,Gary Gilmour,12.0,England,6,14,6,1.16,0,0,0,0,0,2.33,72,12.00,1,6/14
2,Australia VS West Indies,ODI # 33,Max Walker,9.2,England,3,22,3,2.35,0,0,0,0,0,7.33,56,18.67,0,3/22
3,Australia VS West Indies,ODI # 33,Jeff Thomson,6.0,England,0,17,0,2.83,0,0,0,0,0,0.00,36,0.00,0,0/17
4,Australia VS West Indies,ODI # 33,Geoff Arnold,7.4,Australia,2,15,1,1.95,0,0,0,0,0,15.00,46,46.00,0,1/15

In [123]:
batting_data.head()

,VS,Player,,Batting Possition,Match Id,Teaminnings,Runs,Balls,Mins,Fours,Sixs,Strike Rate,Centuries,Half Centuries
0,Australia VS West Indies,Dennis Amiss,lbw b Gilmour,1.0,ODI # 33,England,2.0,7.0,11.0,0.0,0.0,28.57,0,0
1,Australia VS West Indies,Barry Wood,b Gilmour,2.0,ODI # 33,England,6.0,19.0,29.0,1.0,0.0,31.57,0,0
2,Australia VS West Indies,Keith Fletcher,lbw b Gilmour,3.0,ODI # 33,England,8.0,45.0,59.0,0.0,0.0,17.77,0,0
3,Australia VS West Indies,Tony Greig,c â Marsh b Gilmour,4.0,ODI # 33,England,7.0,25.0,24.0,1.0,0.0,28.00,0,0
4,Australia VS West Indies,Frank Hayes,lbw b Gilmour,5.0,ODI # 33,England,4.0,6.0,9.0,1.0,0.0,66.66,0,0

In [148]:
batting_data.merge(bowling_data,on="Player")["Player"].nunique()

794